ssh:
  host: "192.168.1.1:22"
  user: "user"
  key_path: "./id_rsa"

monitoring:
  urls:
    - "https://google.com"
    - "https://github.com"

commands:
  - phrase: "перезагрузи бота"
    script: "docker restart bot-1"
    response: "Готово. Бот перезагружен"

  - phrase: "статус сервера"
    script: "uptime"
    response: "Сервер в порядке. Аптайм: %s"

wol:
  enabled: false
  devices:
    - name: "мой пк"
      mac: "AA:BB:CC:DD:EE:FF"
      broadcast_ip: "255.255.255.255:9"